version: "3"
services:
  playlist_downloader:
    container_name: youtube_playlist_downloader
    image: lukasberk/youtube_playlist_downloader:latest
    build: .
    volumes:
      - './music:/music'
    environment:
      - YOUTUBE_PLAYLIST="https://www.youtube.com/playlist?list=PLzq-VeHKRqxsL7dGmuwx_WLgUCJjY9aje"
      - STORAGE_LOCATION="/music/"