version: "3"
services:
  # TODO use image instead of building
  playlist_downloader:
    container_name: playlist_downloader
    build: .
    environment:
      - YOUTUBE_PLAYLIST_TO_DOWNLOAD="https://www.youtube.com/playlist?list=PLzq-VeHKRqxt28SGskHpKlO10BBGdf2np"



